### ISSUE TITLE
点击网络诊断没反应，还有unexpected send handshake reply

### ISSUE THREAD

**Issue by uoht** [Mythologyli/ZJU-Connect-for-Windows#5]
最新版点击网络诊断没反应，而且之前的问题没有解决
Version: 1.0.0
Windows 11 Version 22H2
2023-09-23 17:18:10 工作模式设置为：RVPN
2023/09/23 17:20:42 Login Request: https://vpn.shou.edu.cn:443/por/login_auth.csp?apiversion=1

2023/09/23 17:20:42 Twf Id: fe970ba6ee081578
2023/09/23 17:20:42 RSA Key: C5622DC9C719567A2F84F19F3C1FAB9C392264AF3FF6D1D7EB40D75D6D2E94245444F54544F3F33A67A90AAC3DB8A21528CA87DB3EB8AA05D22C471C4DB8F9FF9EBD801CE8EF7DB167E3C792D340AAA8DEDCAB4567D5254FB5F681B414BE50C5AC7C494A91D8C3AAD4EFEB7F28717F17844B2B2190A6A890AE8C180A9B72BCFD7325D077D37C46CF6FCB56B0BB0255BD57193DBA4D0F005053B3C560E6ADD9BC06D0EE1F03E86E5233D2F71727D56E3ED076B66BC980A145582591DFE0B381FC84542A9276B8FB6D6D7574A720C7F288B22C0CAEFF6F15E217CCDF0F990A0981F3A23540627B372AB5B6F20800DD9E1546804E20EA68962CDA3A39423F9DF68F

2023/09/23 17:20:42 RSA Exp: 65537
2023/09/23 17:20:42 WARNING: No CSRF Code Match. Maybe you're connecting to an older server? Continue anyway...
2023/09/23 17:20:42 Login Request: https://vpn.shou.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs

2023/09/23 17:20:42 No NextAuth found.
2023/09/23 17:20:42 Web Login process done.

2023/09/23 17:20:42 ECAgent Request: /por/conf.csp & /por/rclist.csp

2023/09/23 17:20:42 Server Session ID: bc3af6dc1983b750dd375d160333cf61cffaec051deadf8a77e99bef0cd7f383

2023/09/23 17:20:42 Parsed /por/conf.csp 

2023/09/23 17:20:43 Parsed /por/rclist.csp 
2023/09/23 17:20:43 try parsing by goXml

2023/09/23 17:20:43 Progress: 0/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 0/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 0/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 1/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 1/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 2/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 2/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 3/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 3/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 3/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 4/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 4/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 5/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 5/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 6/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 6/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 7/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 7/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 7/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 8/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 8/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 9/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 9/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 10/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 10/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 11/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 11/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 11/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 12/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 12/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 13/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 13/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 14/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 14/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 14/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 15/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 15/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 16/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 16/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 17/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 17/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 18/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 18/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 18/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 19/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 19/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 20/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 20/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 21/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 21/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 22/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 22/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 22/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 23/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 23/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 24/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 24/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 25/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 25/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 25/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 26/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 26/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 27/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 27/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 28/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 28/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 29/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 29/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 29/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 30/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 30/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 31/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 31/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 32/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 32/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 33/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 33/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 33/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 34/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 34/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 35/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 35/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 36/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 36/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 37/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 37/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 37/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 38/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 38/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 39/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 39/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 40/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 40/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 40/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 41/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 41/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 42/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 42/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 43/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 43/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 44/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 44/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 44/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 45/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 45/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 46/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 46/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 47/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 47/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 48/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 48/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 48/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 49/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 49/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 50/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 50/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 51/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 51/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 51/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 52/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 52/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 53/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 53/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 54/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 54/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 55/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 55/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 55/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 56/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 56/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 57/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 57/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 58/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 58/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 59/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 59/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 59/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 60/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 60/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 61/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 61/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 62/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 62/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 62/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 63/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 63/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 64/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 64/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 65/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 65/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 66/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 66/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 66/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 67/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 67/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 68/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 68/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 69/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 69/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 70/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 70/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 70/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 71/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 71/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 72/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 72/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 73/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 73/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 74/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 74/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 74/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 75/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 75/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 76/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 76/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 77/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 77/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 77/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 78/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 78/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 79/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 79/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 80/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 80/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 81/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 81/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 81/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 82/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 82/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 83/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 83/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 84/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 84/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 85/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 85/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 85/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 86/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 86/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 87/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 87/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 88/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 88/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 88/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 89/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 89/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 90/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 90/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 91/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 91/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 92/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 92/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 92/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 93/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 93/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 94/100 (ResourceList.Rcs)

2023/09/23 17:20:43 Progress: 94/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 95/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 95/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 96/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 96/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 96/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 97/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 97/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 98/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 98/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 99/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Progress: 99/100 (ResourceList.Rcs)
2023/09/23 17:20:43 Parsed 865 domain rules
2023/09/23 17:20:43 Parsed 5 IPv4 rules
2023/09/23 17:20:43 Parsed 95 DNS rules

2023/09/23 17:20:43 socket: connected to:  58.246.161.76:443
2023/09/23 17:20:43 tls: connected to:  58.246.161.76:443

2023/09/23 17:20:43 Login success, your IP: 172.18.214.105

2023/09/23 17:20:43 HTTP server listening on 127.0.0.1:1081
2023/09/23 17:20:43 SOCKS5 server listening on 127.0.0.1:1080

2023/09/23 17:20:43 socket: connected to:  58.246.161.76:443
2023/09/23 17:20:43 tls: connected to:  58.246.161.76:443
2023/09/23 17:20:43 socket: connected to:  58.246.161.76:443
2023/09/23 17:20:43 tls: connected to:  58.246.161.76:443

2023/09/23 17:20:53 KeepAlive: lookup www.baidu.com on 192.168.5.1:53: read udp 172.18.214.105:45740: i/o timeout

2023/09/23 17:21:53 Error occurred while send, retrying: write tcp 192.168.5.59:55983->58.246.161.76:443: wsasend: An established connection was aborted by the software in your host machine.

2023/09/23 17:21:53 socket: connected to:  58.246.161.76:443
2023/09/23 17:21:53 tls: connected to:  58.246.161.76:443

2023/09/23 17:21:53 Error occurred while send, retrying: unexpected send handshake reply

2023/09/23 17:21:53 socket: connected to:  58.246.161.76:443
2023/09/23 17:21:53 tls: connected to:  58.246.161.76:443

2023/09/23 17:21:53 Error occurred while send, retrying: unexpected send handshake reply

2023/09/23 17:21:53 socket: connected to:  58.246.161.76:443
2023/09/23 17:21:53 tls: connected to:  58.246.161.76:443

2023/09/23 17:21:53 Error occurred while send, retrying: unexpected send handshake reply

2023/09/23 17:21:53 socket: connected to:  58.246.161.76:443
2023/09/23 17:21:53 tls: connected to:  58.246.161.76:443

2023/09/23 17:21:53 Error occurred while send, retrying: unexpected send handshake reply

panic: send retry limit exceeded.

goroutine 114 [running]:
github.com/mythologyli/zju-connect/core.StartProtocol.func2()
	github.com/mythologyli/zju-connect/core/protocol.go:245 +0x14b
created by github.com/mythologyli/zju-connect/core.StartProtocol in goroutine 1
	github.com/mythologyli/zju-connect/core/protocol.go:248 +0x136

2023-09-23 17:21:53 RVPN 断开！

**Comment by Mythologyli** [comment]
这个版本针对 ZJU 网络环境做了许多特化，大多数功能需要 ZJU 校园网环境，推荐退回旧版本使用

**Comment by Mythologyli** [comment]
更新：你可能无法使用 GUI 版，因为 ZJU DNS 无法在 GUI 版中更改

你需要使用命令行版，并设置 disable-zju-config disable-zju-dns
